In [1]:
import pandas as pd

In [6]:
df = pd.read_csv("Cleaned_EV_Data.csv")

In [7]:
df.head()

,VIN (1-10),County,City,State,Postal Code,Model Year,Make,Model,Electric Vehicle Type,Clean Alternative Fuel Vehicle (CAFV) Eligibility,Electric Range,Legislative District,DOL Vehicle ID,Vehicle Location,Electric Utility,2020 Census Tract
0,1N4AZ0CP6D,King,Kirkland,WA,98034.0,2013,NISSAN,LEAF,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,75.0,1.0,154635729,POINT (-122.22901 47.72201),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303302e+10
1,5YJ3E1EC8L,Kitsap,Bainbridge Island,WA,98110.0,2020,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,308.0,23.0,107518645,POINT (-122.521 47.62759),PUGET SOUND ENERGY INC,5.303509e+10
2,5YJ3E1EBXJ,King,Seattle,WA,98144.0,2018,TESLA,MODEL 3,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,215.0,37.0,474808813,POINT (-122.30866 47.57874),CITY OF SEATTLE - (WA)|CITY OF TACOMA - (WA),5.303301e+10
3,ZFAFFAC45R,Thurston,Yelm,WA,98597.0,2024,FIAT,500E,Battery Electric Vehicle (BEV),Eligibility unknown as battery range has not b...,0.0,2.0,273658514,POINT (-122.60735 46.94239),PUGET SOUND ENERGY INC,5.306701e+10
4,5YJYGDEE3L,King,Kent,WA,98030.0,2020,TESLA,MODEL Y,Battery Electric Vehicle (BEV),Clean Alternative Fuel Vehicle Eligible,291.0,47.0,109579900,POINT (-122.19975 47.37483),PUGET SOUND ENERGY INC||CITY OF TACOMA - (WA),5.303303e+10

In [8]:
df.shape

(59999, 16)

In [9]:
df.isna().sum()

VIN (1-10)                                           0
County                                               1
City                                                 1
State                                                0
Postal Code                                          1
Model Year                                           0
Make                                                 0
Model                                                0
Electric Vehicle Type                                0
Clean Alternative Fuel Vehicle (CAFV) Eligibility    0
Electric Range                                       2
Legislative District                                 1
DOL Vehicle ID                                       0
Vehicle Location                                     1
Electric Utility                                     1
2020 Census Tract                                    1
dtype: int64

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 59999 entries, 0 to 59998
Data columns (total 16 columns):
 #   Column                                             Non-Null Count  Dtype
---  ------                                             --------------  -----
 0   VIN (1-10)                                         59999 non-null  str
 1   County                                             59998 non-null  str
 2   City                                               59998 non-null  str
 3   State                                              59999 non-null  str
 4   Postal Code                                        59998 non-null  float64
 5   Model Year                                         59999 non-null  int64
 6   Make                                               59999 non-null  str
 7   Model                                              59999 non-null  str
 8   Electric Vehicle Type                              59999 non-null  str
 9   Clean Alternative Fuel Vehicle (CAFV) Eligibility  59999 non-null  str
 10  Electric Range                                     59997 non-null  float64
 11  Legislative District                               59998 non-null  float64
 12  DOL Vehicle ID                                     59999 non-null  int64
 13  Vehicle Location                                   59998 non-null  str
 14  Electric Utility                                   59998 non-null  str
 15  2020 Census Tract                                  59998 non-null  float64
dtypes: float64(4), int64(2), str(10)
memory usage: 7.3 MB

In [12]:
df.describe()

,Postal Code,Model Year,Electric Range,Legislative District,DOL Vehicle ID,2020 Census Tract
count,59998.000000,59999.000000,59997.000000,59998.000000,5.999900e+04,5.999800e+04
mean,98182.157905,2022.152853,38.965732,32.369879,2.468955e+08,5.303377e+10
std,221.729371,3.027038,77.907658,14.478510,6.407520e+07,1.238545e+07
min,98001.000000,2000.000000,0.000000,1.000000,1.028600e+04,5.300396e+10
25%,98034.000000,2021.000000,0.000000,21.000000,2.235354e+08,5.303301e+10
50%,98106.000000,2023.000000,0.000000,36.000000,2.629412e+08,5.303302e+10
75%,98188.000000,2024.000000,32.000000,45.000000,2.802533e+08,5.303303e+10
max,99403.000000,2027.000000,337.000000,49.000000,4.789259e+08,5.307794e+10